server:
  port: 8085

spring:
  application:
    name: im-service
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST:38.76.188.242}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:}
      database: 3
      timeout: 3s

grpc:
  server:
    port: 9095

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
